### ISSUE TITLE
HTML/CSS小技巧

### ISSUE THREAD

**Issue by ahaow** [ahaow/Blog#18]
# HTML/CSS小技巧

## 清除浮动

```css

.clearfix {
	zoom: 1;
}

.clearfix::after {
	content: "";
	clear: both;
	display: block;
	visibilty: hidden;
	height: 0
}

```

## 控制文本大小

```css

text-transform:

	none // 默认
	caoitailze // 文本中的每一单词以大写字母开头
	lowercase  // 定义无大写字母，仅有大写字母
	uppercase // 定义仅有大写字母
	inherit // 规定从父元素继承text-transform属性的值

```

## 文本溢出 出现省略号

**单行文本：**

```css

text-overflow: ellipsis; // 出现省略号
overflow: hidden;
white-space: nowrap; // 禁止换行

```

**第一种多行文本：**

```css

overflow: hidden;
text-overflow: ellipsis; 
display: -webkit-box; // 必须结合的属性，将对象作为弹性伸缩盒子模型显示；
-webkit-line-clamp: 2; // 可以用来多行文本的情况下，用省略号“...”隐藏超出范围的文本；
-webkit-box-orient: vertical; // 必须结合的属性，设置或检索伸缩对象的子元素的排列方式；

```

**第二种多行文本：**

```css

p {
	
	position: relative;
	line-height: 1.4em;
	height: 4.2em;
	overflow: hidden;
}

p::after {
	content: "...";
	font-weight: bold;
	position: absolute;
	bottom: 0;
	right: 0;
	padding:0 20px 1px 45px;
    background:url(http://newimg88.b0.upaiyun.com/newimg88/2014/09/ellipsis_bg.png) repeat-y;
}

```

**第三种多行文本：**

- 使用split + 正则表达式将单词与单个文字切割出来为一个数组
- 加上'...'
- 判断scrollHeight和clientHeight，超过的话就将数组pop一个出来

```html

<style>
  #box {
     width: 200px;
     height: 80px;
     background: pink;
  }
</style>

<div id='box'>
扭扭捏捏扭扭捏捏扭扭捏捏扭扭捏捏扭扭捏捏扭扭捏捏扭扭捏捏扭扭捏捏男男女女你爱上大搜活动请问我核对
</div>

<script>
     var box = document.getElementById("box");
     var words = box.innerHTML.solit(/(?<=[\u4e00-\u9fa5])|(?<=\w*?\b)/g)
     while(box.scrollHeight > box.clientHeight) {
           words.pop;
           box.innerHTML = words.join('') + '...';
     }
</script>
```

**第四种多行文本：**

clamp.js [地址](https://github.com/josephschmitt/Clamp.js)

## css改变滚动条样式

```css

/*定义滚动条宽高及背景，宽高分别对应横竖滚动条的尺寸*/
::-webkit-scrollbar {
    width: 5px;
    height: 5px;
    background-color: rgba(245, 245, 245, 0.47);
}

/*定义滚动条的轨道，内阴影及圆角*/
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
    border-radius: 10px;
    background-color: #f5f5f5;
}

/*定义滑块，内阴影及圆角*/
::-webkit-scrollbar-thumb {
    /*width: 10px;*/
    height: 20px;
    border-radius: 10px;
    -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
    background-color: rgba(85, 85, 85, 0.25);
}
```

## clipboard

**clipboard.js** 是一个在浏览器上 拷贝文字 的一个库

在**ios**上，绑定 属性，方法的元素 不能是 `div` , 要是用 `button` 标签
