### ISSUE TITLE
三栏布局： 两边固定 中间自适应 

### ISSUE THREAD

**Issue by ahaow** [ahaow/Blog#5]
# 页面布局

### 假设高度已知，请写出三栏布局，其中左栏，右栏宽度各位300px，中间自适应

```html
<section class="layout float">
  <article class="box">
    <div class="left"></div>
    <div class="right"></div>
    <div class="center">
      今天是2019/03/04,天气阳光明媚
      今天是2019/03/04,天气阳光明媚
      今天是2019/03/04,天气阳光明媚
    </div>
  </article>
</section>
```

### 1、浮动解决方案

```css
// 1.浮动解决方案
<style>
  html * {
     margin: 0;
     padding: 0;
  }
   .layout .box div {
    min-height: 100px;
  }
  .layout.float .left {
    float: left;
    width: 300px;
    background: red;
  }            
  .layout.float .right {
    float: right;
    width: 300px;
    background: blue;
  }            
  .layout.float .center {
    background: yellow;
  }            
</style>            
```

### 2、绝对定位写法

```css
// 2、绝对定位写法
html * {
  margin: 0;
  padding: 0;
}
.layout.absolute > .box > div {
  min-height: 100px;
  position: absolute;
}
.layout.absolute > .box > .left {
  left: 0;
  width: 300px;
  background: red;
}
.layout.absolute > .box > .center {
  left: 300px;
  right: 300px;
  background: yellow;
}
.layout.absolute > .box > .right {
  right: 0;
  width: 300px;
  background: blue;
}
```

### 3、flex布局

```css
// flex布局
.layout.flexbox > .box > div {
  min-height: 100px;
}
.layout.flexbox > .box {
  display: flex;
}
.layout.flexbox > .box > .left {
  width: 300px;
  background: red;
}
.layout.flexbox > .box > .center {
  flex: 1;
  background: yellow;
}
.layout.flexbox > .box > .right {
  width: 300px;
  background: blue;
}
```

### 4、table(表格)布局

```css
// table(表格)写法
.layout.table > .box {
  display: table;
  width: 100%;
  height: 100px;
}
.layout.table > .box > div {
  display: table-cell;
}
.layout.table > .box > .left {
  width: 300px;
  background: red;
}
.layout.table > .box > .center {
  background: yellow;
}
.layout.table > .box > .right {
  width: 300px;
  background: blue;
}
```

### 5、grid(网格)布局

```css
// grid(网格)布局
.layout.grid > .box {
  display: grid;
  width: 100%;
  grid-template-rows: 100px;
  grid-template-columns: 300px auto 300px;
}
.layout.grid > .box > .left {
  background: red;
}
.layout.grid > .box > .center {
  background: yellow;
}
.layout.grid > .box > .right {
  background: blue;
}
```

### 注意：如果高度改为未知，那么只有flex布局 和 表格布局 还能使用，其他都不能使用了。
